// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	readmodels "github.com/raphaeldiscky/go-food-micro/internal/services/orderservice/internal/orders/models/orders/readmodels"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/raphaeldiscky/go-food-micro/internal/pkg/utils"

	uuid "github.com/satori/go.uuid"
)

// orderReadRepository is an autogenerated mock type for the orderReadRepository type
type orderReadRepository struct {
	mock.Mock
}

type orderReadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *orderReadRepository) EXPECT() *orderReadRepository_Expecter {
	return &orderReadRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *orderReadRepository) CreateOrder(ctx context.Context, order *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error) {
	ret := _m.Called(ctx, order)

	var r0 *readmodels.OrderReadModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *readmodels.OrderReadModel) *readmodels.OrderReadModel); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*readmodels.OrderReadModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *readmodels.OrderReadModel) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type orderReadRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *readmodels.OrderReadModel
func (_e *orderReadRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *orderReadRepository_CreateOrder_Call {
	return &orderReadRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *orderReadRepository_CreateOrder_Call) Run(run func(ctx context.Context, order *readmodels.OrderReadModel)) *orderReadRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*readmodels.OrderReadModel))
	})
	return _c
}

func (_c *orderReadRepository_CreateOrder_Call) Return(_a0 *readmodels.OrderReadModel, _a1 error) *orderReadRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error)) *orderReadRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrderByID provides a mock function with given fields: ctx, _a1
func (_m *orderReadRepository) DeleteOrderByID(ctx context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// orderReadRepository_DeleteOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrderByID'
type orderReadRepository_DeleteOrderByID_Call struct {
	*mock.Call
}

// DeleteOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *orderReadRepository_Expecter) DeleteOrderByID(ctx interface{}, _a1 interface{}) *orderReadRepository_DeleteOrderByID_Call {
	return &orderReadRepository_DeleteOrderByID_Call{Call: _e.mock.On("DeleteOrderByID", ctx, _a1)}
}

func (_c *orderReadRepository_DeleteOrderByID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *orderReadRepository_DeleteOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *orderReadRepository_DeleteOrderByID_Call) Return(_a0 error) *orderReadRepository_DeleteOrderByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *orderReadRepository_DeleteOrderByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *orderReadRepository_DeleteOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function with given fields: ctx, listQuery
func (_m *orderReadRepository) GetAllOrders(ctx context.Context, listQuery *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error) {
	ret := _m.Called(ctx, listQuery)

	var r0 *utils.ListResult[*readmodels.OrderReadModel]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error)); ok {
		return rf(ctx, listQuery)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *utils.ListQuery) *utils.ListResult[*readmodels.OrderReadModel]); ok {
		r0 = rf(ctx, listQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ListResult[*readmodels.OrderReadModel])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *utils.ListQuery) error); ok {
		r1 = rf(ctx, listQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type orderReadRepository_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - listQuery *utils.ListQuery
func (_e *orderReadRepository_Expecter) GetAllOrders(ctx interface{}, listQuery interface{}) *orderReadRepository_GetAllOrders_Call {
	return &orderReadRepository_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, listQuery)}
}

func (_c *orderReadRepository_GetAllOrders_Call) Run(run func(ctx context.Context, listQuery *utils.ListQuery)) *orderReadRepository_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*utils.ListQuery))
	})
	return _c
}

func (_c *orderReadRepository_GetAllOrders_Call) Return(_a0 *utils.ListResult[*readmodels.OrderReadModel], _a1 error) *orderReadRepository_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_GetAllOrders_Call) RunAndReturn(run func(context.Context, *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error)) *orderReadRepository_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function with given fields: ctx, _a1
func (_m *orderReadRepository) GetOrderByID(ctx context.Context, _a1 uuid.UUID) (*readmodels.OrderReadModel, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *readmodels.OrderReadModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*readmodels.OrderReadModel, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *readmodels.OrderReadModel); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*readmodels.OrderReadModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type orderReadRepository_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *orderReadRepository_Expecter) GetOrderByID(ctx interface{}, _a1 interface{}) *orderReadRepository_GetOrderByID_Call {
	return &orderReadRepository_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, _a1)}
}

func (_c *orderReadRepository_GetOrderByID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *orderReadRepository_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *orderReadRepository_GetOrderByID_Call) Return(_a0 *readmodels.OrderReadModel, _a1 error) *orderReadRepository_GetOrderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_GetOrderByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*readmodels.OrderReadModel, error)) *orderReadRepository_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByOrderId provides a mock function with given fields: ctx, orderId
func (_m *orderReadRepository) GetOrderByOrderId(ctx context.Context, orderId uuid.UUID) (*readmodels.OrderReadModel, error) {
	ret := _m.Called(ctx, orderId)

	var r0 *readmodels.OrderReadModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*readmodels.OrderReadModel, error)); ok {
		return rf(ctx, orderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *readmodels.OrderReadModel); ok {
		r0 = rf(ctx, orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*readmodels.OrderReadModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_GetOrderByOrderId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByOrderId'
type orderReadRepository_GetOrderByOrderId_Call struct {
	*mock.Call
}

// GetOrderByOrderId is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
func (_e *orderReadRepository_Expecter) GetOrderByOrderId(ctx interface{}, orderId interface{}) *orderReadRepository_GetOrderByOrderId_Call {
	return &orderReadRepository_GetOrderByOrderId_Call{Call: _e.mock.On("GetOrderByOrderId", ctx, orderId)}
}

func (_c *orderReadRepository_GetOrderByOrderId_Call) Run(run func(ctx context.Context, orderId uuid.UUID)) *orderReadRepository_GetOrderByOrderId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *orderReadRepository_GetOrderByOrderId_Call) Return(_a0 *readmodels.OrderReadModel, _a1 error) *orderReadRepository_GetOrderByOrderId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_GetOrderByOrderId_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*readmodels.OrderReadModel, error)) *orderReadRepository_GetOrderByOrderId_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOrders provides a mock function with given fields: ctx, searchText, listQuery
func (_m *orderReadRepository) SearchOrders(ctx context.Context, searchText string, listQuery *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error) {
	ret := _m.Called(ctx, searchText, listQuery)

	var r0 *utils.ListResult[*readmodels.OrderReadModel]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error)); ok {
		return rf(ctx, searchText, listQuery)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *utils.ListQuery) *utils.ListResult[*readmodels.OrderReadModel]); ok {
		r0 = rf(ctx, searchText, listQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ListResult[*readmodels.OrderReadModel])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *utils.ListQuery) error); ok {
		r1 = rf(ctx, searchText, listQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_SearchOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOrders'
type orderReadRepository_SearchOrders_Call struct {
	*mock.Call
}

// SearchOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - searchText string
//   - listQuery *utils.ListQuery
func (_e *orderReadRepository_Expecter) SearchOrders(ctx interface{}, searchText interface{}, listQuery interface{}) *orderReadRepository_SearchOrders_Call {
	return &orderReadRepository_SearchOrders_Call{Call: _e.mock.On("SearchOrders", ctx, searchText, listQuery)}
}

func (_c *orderReadRepository_SearchOrders_Call) Run(run func(ctx context.Context, searchText string, listQuery *utils.ListQuery)) *orderReadRepository_SearchOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*utils.ListQuery))
	})
	return _c
}

func (_c *orderReadRepository_SearchOrders_Call) Return(_a0 *utils.ListResult[*readmodels.OrderReadModel], _a1 error) *orderReadRepository_SearchOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_SearchOrders_Call) RunAndReturn(run func(context.Context, string, *utils.ListQuery) (*utils.ListResult[*readmodels.OrderReadModel], error)) *orderReadRepository_SearchOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, order
func (_m *orderReadRepository) UpdateOrder(ctx context.Context, order *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error) {
	ret := _m.Called(ctx, order)

	var r0 *readmodels.OrderReadModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *readmodels.OrderReadModel) *readmodels.OrderReadModel); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*readmodels.OrderReadModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *readmodels.OrderReadModel) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// orderReadRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type orderReadRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *readmodels.OrderReadModel
func (_e *orderReadRepository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *orderReadRepository_UpdateOrder_Call {
	return &orderReadRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *orderReadRepository_UpdateOrder_Call) Run(run func(ctx context.Context, order *readmodels.OrderReadModel)) *orderReadRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*readmodels.OrderReadModel))
	})
	return _c
}

func (_c *orderReadRepository_UpdateOrder_Call) Return(_a0 *readmodels.OrderReadModel, _a1 error) *orderReadRepository_UpdateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *orderReadRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, *readmodels.OrderReadModel) (*readmodels.OrderReadModel, error)) *orderReadRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// newOrderReadRepository creates a new instance of orderReadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOrderReadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *orderReadRepository {
	mock := &orderReadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
