// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	appendresult "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models/appendresult"

	mock "github.com/stretchr/testify/mock"

	models "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models"

	readposition "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models/streamposition/readposition"

	streamname "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models/streamname"

	streamversion "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models/streamversion"

	truncateposition "github.com/raphaeldiscky/go-food-micro/internal/pkg/es/models/streamposition/truncateposition"
)

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

type EventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EventStore) EXPECT() *EventStore_Expecter {
	return &EventStore_Expecter{mock: &_m.Mock}
}

// AppendEvents provides a mock function with given fields: streamName, expectedVersion, events, ctx
func (_m *EventStore) AppendEvents(streamName streamname.StreamName, expectedVersion streamversion.ExpectedStreamVersion, events []*models.StreamEvent, ctx context.Context) (*appendresult.AppendEventsResult, error) {
	ret := _m.Called(streamName, expectedVersion, events, ctx)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvents")
	}

	var r0 *appendresult.AppendEventsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, streamversion.ExpectedStreamVersion, []*models.StreamEvent, context.Context) (*appendresult.AppendEventsResult, error)); ok {
		return rf(streamName, expectedVersion, events, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, streamversion.ExpectedStreamVersion, []*models.StreamEvent, context.Context) *appendresult.AppendEventsResult); ok {
		r0 = rf(streamName, expectedVersion, events, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appendresult.AppendEventsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, streamversion.ExpectedStreamVersion, []*models.StreamEvent, context.Context) error); ok {
		r1 = rf(streamName, expectedVersion, events, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_AppendEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvents'
type EventStore_AppendEvents_Call struct {
	*mock.Call
}

// AppendEvents is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - expectedVersion streamversion.ExpectedStreamVersion
//   - events []*models.StreamEvent
//   - ctx context.Context
func (_e *EventStore_Expecter) AppendEvents(streamName interface{}, expectedVersion interface{}, events interface{}, ctx interface{}) *EventStore_AppendEvents_Call {
	return &EventStore_AppendEvents_Call{Call: _e.mock.On("AppendEvents", streamName, expectedVersion, events, ctx)}
}

func (_c *EventStore_AppendEvents_Call) Run(run func(streamName streamname.StreamName, expectedVersion streamversion.ExpectedStreamVersion, events []*models.StreamEvent, ctx context.Context)) *EventStore_AppendEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(streamversion.ExpectedStreamVersion), args[2].([]*models.StreamEvent), args[3].(context.Context))
	})
	return _c
}

func (_c *EventStore_AppendEvents_Call) Return(_a0 *appendresult.AppendEventsResult, _a1 error) *EventStore_AppendEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_AppendEvents_Call) RunAndReturn(run func(streamname.StreamName, streamversion.ExpectedStreamVersion, []*models.StreamEvent, context.Context) (*appendresult.AppendEventsResult, error)) *EventStore_AppendEvents_Call {
	_c.Call.Return(run)
	return _c
}

// AppendNewEvents provides a mock function with given fields: streamName, events, ctx
func (_m *EventStore) AppendNewEvents(streamName streamname.StreamName, events []*models.StreamEvent, ctx context.Context) (*appendresult.AppendEventsResult, error) {
	ret := _m.Called(streamName, events, ctx)

	if len(ret) == 0 {
		panic("no return value specified for AppendNewEvents")
	}

	var r0 *appendresult.AppendEventsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, []*models.StreamEvent, context.Context) (*appendresult.AppendEventsResult, error)); ok {
		return rf(streamName, events, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, []*models.StreamEvent, context.Context) *appendresult.AppendEventsResult); ok {
		r0 = rf(streamName, events, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appendresult.AppendEventsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, []*models.StreamEvent, context.Context) error); ok {
		r1 = rf(streamName, events, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_AppendNewEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendNewEvents'
type EventStore_AppendNewEvents_Call struct {
	*mock.Call
}

// AppendNewEvents is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - events []*models.StreamEvent
//   - ctx context.Context
func (_e *EventStore_Expecter) AppendNewEvents(streamName interface{}, events interface{}, ctx interface{}) *EventStore_AppendNewEvents_Call {
	return &EventStore_AppendNewEvents_Call{Call: _e.mock.On("AppendNewEvents", streamName, events, ctx)}
}

func (_c *EventStore_AppendNewEvents_Call) Run(run func(streamName streamname.StreamName, events []*models.StreamEvent, ctx context.Context)) *EventStore_AppendNewEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].([]*models.StreamEvent), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_AppendNewEvents_Call) Return(_a0 *appendresult.AppendEventsResult, _a1 error) *EventStore_AppendNewEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_AppendNewEvents_Call) RunAndReturn(run func(streamname.StreamName, []*models.StreamEvent, context.Context) (*appendresult.AppendEventsResult, error)) *EventStore_AppendNewEvents_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStream provides a mock function with given fields: streamName, expectedVersion, ctx
func (_m *EventStore) DeleteStream(streamName streamname.StreamName, expectedVersion streamversion.ExpectedStreamVersion, ctx context.Context) error {
	ret := _m.Called(streamName, expectedVersion, ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, streamversion.ExpectedStreamVersion, context.Context) error); ok {
		r0 = rf(streamName, expectedVersion, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventStore_DeleteStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStream'
type EventStore_DeleteStream_Call struct {
	*mock.Call
}

// DeleteStream is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - expectedVersion streamversion.ExpectedStreamVersion
//   - ctx context.Context
func (_e *EventStore_Expecter) DeleteStream(streamName interface{}, expectedVersion interface{}, ctx interface{}) *EventStore_DeleteStream_Call {
	return &EventStore_DeleteStream_Call{Call: _e.mock.On("DeleteStream", streamName, expectedVersion, ctx)}
}

func (_c *EventStore_DeleteStream_Call) Run(run func(streamName streamname.StreamName, expectedVersion streamversion.ExpectedStreamVersion, ctx context.Context)) *EventStore_DeleteStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(streamversion.ExpectedStreamVersion), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_DeleteStream_Call) Return(_a0 error) *EventStore_DeleteStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventStore_DeleteStream_Call) RunAndReturn(run func(streamname.StreamName, streamversion.ExpectedStreamVersion, context.Context) error) *EventStore_DeleteStream_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEvents provides a mock function with given fields: streamName, readPosition, count, ctx
func (_m *EventStore) ReadEvents(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, count uint64, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(streamName, readPosition, count, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEvents")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(streamName, readPosition, count, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) []*models.StreamEvent); ok {
		r0 = rf(streamName, readPosition, count, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) error); ok {
		r1 = rf(streamName, readPosition, count, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEvents'
type EventStore_ReadEvents_Call struct {
	*mock.Call
}

// ReadEvents is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - readPosition readposition.StreamReadPosition
//   - count uint64
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEvents(streamName interface{}, readPosition interface{}, count interface{}, ctx interface{}) *EventStore_ReadEvents_Call {
	return &EventStore_ReadEvents_Call{Call: _e.mock.On("ReadEvents", streamName, readPosition, count, ctx)}
}

func (_c *EventStore_ReadEvents_Call) Run(run func(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, count uint64, ctx context.Context)) *EventStore_ReadEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(readposition.StreamReadPosition), args[2].(uint64), args[3].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEvents_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEvents_Call) RunAndReturn(run func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEventsBackwards provides a mock function with given fields: streamName, readPosition, count, ctx
func (_m *EventStore) ReadEventsBackwards(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, count uint64, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(streamName, readPosition, count, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEventsBackwards")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(streamName, readPosition, count, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) []*models.StreamEvent); ok {
		r0 = rf(streamName, readPosition, count, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) error); ok {
		r1 = rf(streamName, readPosition, count, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEventsBackwards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEventsBackwards'
type EventStore_ReadEventsBackwards_Call struct {
	*mock.Call
}

// ReadEventsBackwards is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - readPosition readposition.StreamReadPosition
//   - count uint64
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEventsBackwards(streamName interface{}, readPosition interface{}, count interface{}, ctx interface{}) *EventStore_ReadEventsBackwards_Call {
	return &EventStore_ReadEventsBackwards_Call{Call: _e.mock.On("ReadEventsBackwards", streamName, readPosition, count, ctx)}
}

func (_c *EventStore_ReadEventsBackwards_Call) Run(run func(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, count uint64, ctx context.Context)) *EventStore_ReadEventsBackwards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(readposition.StreamReadPosition), args[2].(uint64), args[3].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEventsBackwards_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEventsBackwards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEventsBackwards_Call) RunAndReturn(run func(streamname.StreamName, readposition.StreamReadPosition, uint64, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEventsBackwards_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEventsBackwardsFromEnd provides a mock function with given fields: streamName, count, ctx
func (_m *EventStore) ReadEventsBackwardsFromEnd(streamName streamname.StreamName, count uint64, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(streamName, count, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEventsBackwardsFromEnd")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, uint64, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(streamName, count, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, uint64, context.Context) []*models.StreamEvent); ok {
		r0 = rf(streamName, count, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, uint64, context.Context) error); ok {
		r1 = rf(streamName, count, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEventsBackwardsFromEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEventsBackwardsFromEnd'
type EventStore_ReadEventsBackwardsFromEnd_Call struct {
	*mock.Call
}

// ReadEventsBackwardsFromEnd is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - count uint64
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEventsBackwardsFromEnd(streamName interface{}, count interface{}, ctx interface{}) *EventStore_ReadEventsBackwardsFromEnd_Call {
	return &EventStore_ReadEventsBackwardsFromEnd_Call{Call: _e.mock.On("ReadEventsBackwardsFromEnd", streamName, count, ctx)}
}

func (_c *EventStore_ReadEventsBackwardsFromEnd_Call) Run(run func(streamName streamname.StreamName, count uint64, ctx context.Context)) *EventStore_ReadEventsBackwardsFromEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(uint64), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEventsBackwardsFromEnd_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEventsBackwardsFromEnd_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEventsBackwardsFromEnd_Call) RunAndReturn(run func(streamname.StreamName, uint64, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEventsBackwardsFromEnd_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEventsBackwardsWithMaxCount provides a mock function with given fields: stream, readPosition, ctx
func (_m *EventStore) ReadEventsBackwardsWithMaxCount(stream streamname.StreamName, readPosition readposition.StreamReadPosition, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(stream, readPosition, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEventsBackwardsWithMaxCount")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(stream, readPosition, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) []*models.StreamEvent); ok {
		r0 = rf(stream, readPosition, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) error); ok {
		r1 = rf(stream, readPosition, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEventsBackwardsWithMaxCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEventsBackwardsWithMaxCount'
type EventStore_ReadEventsBackwardsWithMaxCount_Call struct {
	*mock.Call
}

// ReadEventsBackwardsWithMaxCount is a helper method to define mock.On call
//   - stream streamname.StreamName
//   - readPosition readposition.StreamReadPosition
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEventsBackwardsWithMaxCount(stream interface{}, readPosition interface{}, ctx interface{}) *EventStore_ReadEventsBackwardsWithMaxCount_Call {
	return &EventStore_ReadEventsBackwardsWithMaxCount_Call{Call: _e.mock.On("ReadEventsBackwardsWithMaxCount", stream, readPosition, ctx)}
}

func (_c *EventStore_ReadEventsBackwardsWithMaxCount_Call) Run(run func(stream streamname.StreamName, readPosition readposition.StreamReadPosition, ctx context.Context)) *EventStore_ReadEventsBackwardsWithMaxCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(readposition.StreamReadPosition), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEventsBackwardsWithMaxCount_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEventsBackwardsWithMaxCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEventsBackwardsWithMaxCount_Call) RunAndReturn(run func(streamname.StreamName, readposition.StreamReadPosition, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEventsBackwardsWithMaxCount_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEventsFromStart provides a mock function with given fields: streamName, count, ctx
func (_m *EventStore) ReadEventsFromStart(streamName streamname.StreamName, count uint64, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(streamName, count, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEventsFromStart")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, uint64, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(streamName, count, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, uint64, context.Context) []*models.StreamEvent); ok {
		r0 = rf(streamName, count, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, uint64, context.Context) error); ok {
		r1 = rf(streamName, count, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEventsFromStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEventsFromStart'
type EventStore_ReadEventsFromStart_Call struct {
	*mock.Call
}

// ReadEventsFromStart is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - count uint64
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEventsFromStart(streamName interface{}, count interface{}, ctx interface{}) *EventStore_ReadEventsFromStart_Call {
	return &EventStore_ReadEventsFromStart_Call{Call: _e.mock.On("ReadEventsFromStart", streamName, count, ctx)}
}

func (_c *EventStore_ReadEventsFromStart_Call) Run(run func(streamName streamname.StreamName, count uint64, ctx context.Context)) *EventStore_ReadEventsFromStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(uint64), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEventsFromStart_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEventsFromStart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEventsFromStart_Call) RunAndReturn(run func(streamname.StreamName, uint64, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEventsFromStart_Call {
	_c.Call.Return(run)
	return _c
}

// ReadEventsWithMaxCount provides a mock function with given fields: streamName, readPosition, ctx
func (_m *EventStore) ReadEventsWithMaxCount(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, ctx context.Context) ([]*models.StreamEvent, error) {
	ret := _m.Called(streamName, readPosition, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadEventsWithMaxCount")
	}

	var r0 []*models.StreamEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) ([]*models.StreamEvent, error)); ok {
		return rf(streamName, readPosition, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) []*models.StreamEvent); ok {
		r0 = rf(streamName, readPosition, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.StreamEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, readposition.StreamReadPosition, context.Context) error); ok {
		r1 = rf(streamName, readPosition, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_ReadEventsWithMaxCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadEventsWithMaxCount'
type EventStore_ReadEventsWithMaxCount_Call struct {
	*mock.Call
}

// ReadEventsWithMaxCount is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - readPosition readposition.StreamReadPosition
//   - ctx context.Context
func (_e *EventStore_Expecter) ReadEventsWithMaxCount(streamName interface{}, readPosition interface{}, ctx interface{}) *EventStore_ReadEventsWithMaxCount_Call {
	return &EventStore_ReadEventsWithMaxCount_Call{Call: _e.mock.On("ReadEventsWithMaxCount", streamName, readPosition, ctx)}
}

func (_c *EventStore_ReadEventsWithMaxCount_Call) Run(run func(streamName streamname.StreamName, readPosition readposition.StreamReadPosition, ctx context.Context)) *EventStore_ReadEventsWithMaxCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(readposition.StreamReadPosition), args[2].(context.Context))
	})
	return _c
}

func (_c *EventStore_ReadEventsWithMaxCount_Call) Return(_a0 []*models.StreamEvent, _a1 error) *EventStore_ReadEventsWithMaxCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_ReadEventsWithMaxCount_Call) RunAndReturn(run func(streamname.StreamName, readposition.StreamReadPosition, context.Context) ([]*models.StreamEvent, error)) *EventStore_ReadEventsWithMaxCount_Call {
	_c.Call.Return(run)
	return _c
}

// StreamExists provides a mock function with given fields: streamName, ctx
func (_m *EventStore) StreamExists(streamName streamname.StreamName, ctx context.Context) (bool, error) {
	ret := _m.Called(streamName, ctx)

	if len(ret) == 0 {
		panic("no return value specified for StreamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, context.Context) (bool, error)); ok {
		return rf(streamName, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, context.Context) bool); ok {
		r0 = rf(streamName, ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, context.Context) error); ok {
		r1 = rf(streamName, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_StreamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamExists'
type EventStore_StreamExists_Call struct {
	*mock.Call
}

// StreamExists is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - ctx context.Context
func (_e *EventStore_Expecter) StreamExists(streamName interface{}, ctx interface{}) *EventStore_StreamExists_Call {
	return &EventStore_StreamExists_Call{Call: _e.mock.On("StreamExists", streamName, ctx)}
}

func (_c *EventStore_StreamExists_Call) Run(run func(streamName streamname.StreamName, ctx context.Context)) *EventStore_StreamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(context.Context))
	})
	return _c
}

func (_c *EventStore_StreamExists_Call) Return(_a0 bool, _a1 error) *EventStore_StreamExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_StreamExists_Call) RunAndReturn(run func(streamname.StreamName, context.Context) (bool, error)) *EventStore_StreamExists_Call {
	_c.Call.Return(run)
	return _c
}

// TruncateStream provides a mock function with given fields: streamName, truncatePosition, expectedVersion, ctx
func (_m *EventStore) TruncateStream(streamName streamname.StreamName, truncatePosition truncateposition.StreamTruncatePosition, expectedVersion streamversion.ExpectedStreamVersion, ctx context.Context) (*appendresult.AppendEventsResult, error) {
	ret := _m.Called(streamName, truncatePosition, expectedVersion, ctx)

	if len(ret) == 0 {
		panic("no return value specified for TruncateStream")
	}

	var r0 *appendresult.AppendEventsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(streamname.StreamName, truncateposition.StreamTruncatePosition, streamversion.ExpectedStreamVersion, context.Context) (*appendresult.AppendEventsResult, error)); ok {
		return rf(streamName, truncatePosition, expectedVersion, ctx)
	}
	if rf, ok := ret.Get(0).(func(streamname.StreamName, truncateposition.StreamTruncatePosition, streamversion.ExpectedStreamVersion, context.Context) *appendresult.AppendEventsResult); ok {
		r0 = rf(streamName, truncatePosition, expectedVersion, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appendresult.AppendEventsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(streamname.StreamName, truncateposition.StreamTruncatePosition, streamversion.ExpectedStreamVersion, context.Context) error); ok {
		r1 = rf(streamName, truncatePosition, expectedVersion, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_TruncateStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TruncateStream'
type EventStore_TruncateStream_Call struct {
	*mock.Call
}

// TruncateStream is a helper method to define mock.On call
//   - streamName streamname.StreamName
//   - truncatePosition truncateposition.StreamTruncatePosition
//   - expectedVersion streamversion.ExpectedStreamVersion
//   - ctx context.Context
func (_e *EventStore_Expecter) TruncateStream(streamName interface{}, truncatePosition interface{}, expectedVersion interface{}, ctx interface{}) *EventStore_TruncateStream_Call {
	return &EventStore_TruncateStream_Call{Call: _e.mock.On("TruncateStream", streamName, truncatePosition, expectedVersion, ctx)}
}

func (_c *EventStore_TruncateStream_Call) Run(run func(streamName streamname.StreamName, truncatePosition truncateposition.StreamTruncatePosition, expectedVersion streamversion.ExpectedStreamVersion, ctx context.Context)) *EventStore_TruncateStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(streamname.StreamName), args[1].(truncateposition.StreamTruncatePosition), args[2].(streamversion.ExpectedStreamVersion), args[3].(context.Context))
	})
	return _c
}

func (_c *EventStore_TruncateStream_Call) Return(_a0 *appendresult.AppendEventsResult, _a1 error) *EventStore_TruncateStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_TruncateStream_Call) RunAndReturn(run func(streamname.StreamName, truncateposition.StreamTruncatePosition, streamversion.ExpectedStreamVersion, context.Context) (*appendresult.AppendEventsResult, error)) *EventStore_TruncateStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventStore creates a new instance of EventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventStore {
	mock := &EventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
