// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	integration "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/shared/testfixtures/integration"
	mock "github.com/stretchr/testify/mock"
)

// CatalogUnitOfWork is an autogenerated mock type for the CatalogUnitOfWork type
type CatalogUnitOfWork struct {
	mock.Mock
}

type CatalogUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *CatalogUnitOfWork) EXPECT() *CatalogUnitOfWork_Expecter {
	return &CatalogUnitOfWork_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *CatalogUnitOfWork) Do(ctx context.Context, fn func(integration.CatalogContext) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(integration.CatalogContext) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CatalogUnitOfWork_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type CatalogUnitOfWork_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(integration.CatalogContext) error
func (_e *CatalogUnitOfWork_Expecter) Do(ctx interface{}, fn interface{}) *CatalogUnitOfWork_Do_Call {
	return &CatalogUnitOfWork_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *CatalogUnitOfWork_Do_Call) Run(run func(ctx context.Context, fn func(integration.CatalogContext) error)) *CatalogUnitOfWork_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(integration.CatalogContext) error))
	})
	return _c
}

func (_c *CatalogUnitOfWork_Do_Call) Return(_a0 error) *CatalogUnitOfWork_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CatalogUnitOfWork_Do_Call) RunAndReturn(run func(context.Context, func(integration.CatalogContext) error) error) *CatalogUnitOfWork_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewCatalogUnitOfWork creates a new instance of CatalogUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogUnitOfWork {
	mock := &CatalogUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
