# .depguard.yml configuration
rules:
  # Main is the set of rules for linting main packages
  Main:
    # List of allowed packages
    listMode: allow
    # Only permit stdlib imports, and any third-party package imports
    files:
      - "**/*.go"
    packages:
      - "github.com/pterm/pterm"
      - "github.com/pterm/pterm/putils"
      - "github.com/spf13/cobra"
      - "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/shared/app"
      - "github.com/raphaeldiscky/go-food-micro/internal/pkg/core/web/route"
      - "github.com/raphaeldiscky/go-food-micro/internal/pkg/mapper"
      - "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/products/data/datamodels"
      - "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/products/dtos/v1"
      - "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/products/models"
      - "github.com/raphaeldiscky/go-food-micro/internal/services/catalogwriteservice/internal/shared/grpc/genproto"
      - "google.golang.org/protobuf/types/known/timestamppb"
      - $gostd # This allows any standard library package
    # Include package patterns that would otherwise be blocked
    ignore:
      - "github.com/raphaeldiscky/go-food-micro/**"
